#make file for fLPS 2.0 package 

all: 
	gcc -O2 -march=native -o fLPS2 fLPS2.c -lm 
	gcc -O2 -march=native -o DomainFilter DomainFilter.c -lm 
	gcc -O2 -march=native -o CompositionMaker CompositionMaker.c -lm 
	